[build]
  # 빌드 명령어(필요시 수정)
  command = "npm install && npm run build"
  # 배포할 정적 파일 디렉토리
  publish = "frontend"
  # 서버리스 함수 디렉토리
  functions = "netlify/functions"

# 리다이렉트 설정
[[redirects]]
  from = "/api/auth/user"
  to = "/.netlify/functions/auth-user"
  status = 200
  force = true

[[redirects]]
  from = "/.netlify/functions/api/auth/user"
  to = "/.netlify/functions/auth-user"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/refresh-token"
  to = "/.netlify/functions/refresh-token"
  status = 200
  force = true

[[redirects]]
  from = "/.netlify/functions/api/auth/refresh-token"
  to = "/.netlify/functions/refresh-token"
  status = 200
  force = true

# 모든 경로를 index.html로 리다이렉트 (SPA 지원)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200