[build]
  command = "echo 'Skipping build step - static site'"
  publish = "frontend"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js", "pg"]
  
  # 함수별 설정
  [functions.stores_user_platform]
    included_files = []
    timeout = 30
  
  [functions.stats-details]
    included_files = []
    timeout = 30
    
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# 일반 API 경로 처리 (캐치올 리다이렉트)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# 매장 관련 API 경로 (쿼리 파라미터 사용)
[[redirects]]
  from = "/api/user/:userId/stores"
  to = "/.netlify/functions/user-stores"
  status = 200
  query = {userId = ":userId"}
  force = true

[[redirects]]
  from = "/api/stores/user/:userId/stores"
  to = "/.netlify/functions/stores-user-stores"
  status = 200
  query = {userId = ":userId"}
  force = true

[[redirects]]
  from = "/api/users/:userId/stores"
  to = "/.netlify/functions/users-stores"
  status = 200
  query = {userId = ":userId"}
  force = true

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200
  force = true

  [[redirects]]
  from = "/api/stats_detail*"
  to = "/.netlify/functions/stats-details:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/stats_details*"
  to = "/.netlify/functions/stats-details:splat"
  status = 200
  force = true

# 규칙 세부 정보 API (path 파라미터 사용)
[[redirects]]
  from = "/api/rules/:ruleId"
  to = "/.netlify/functions/rules-detail/:ruleId"
  status = 200
  force = true
  
[[redirects]]
  from = "/api/stores-user-platform"
  to = "/.netlify/functions/stores_user_platform"
  status = 200
  force = true

[[redirects]]
  from = "/api/stores_user_platform"
  to = "/.netlify/functions/stores_user_platform"
  status = 200
  force = true

# 통계 API 경로 추가 - 다양한 표기법에 대응
[[redirects]]
  from = "/api/stats-details"
  to = "/.netlify/functions/stats-details"
  status = 200
  force = true

[[redirects]]
  from = "/api/stats_details"
  to = "/.netlify/functions/stats-details"
  status = 200
  force = true

[[redirects]]
  from = "/api/stats-detail"
  to = "/.netlify/functions/stats-details"
  status = 200
  force = true

[[redirects]]
  from = "/api/stats_detail"
  to = "/.netlify/functions/stats-details"
  status = 200
  force = true

  # 운영자용 모든 매장 조회 라우트 추가
[[redirects]]
  from = "/api/stores/all"
  to = "/.netlify/functions/stores-all"
  status = 200
  force = true

[[redirects]]
  from = "/api/stores_all"
  to = "/.netlify/functions/stores-all"
  status = 200
  force = true

  [[redirects]]
  from = "/api/signin"
  to = "/.netlify/functions/signin"
  status = 200
  force = true

# Netlify 내장 authService 경로
[[redirects]]
  from = "/.netlify/auth/*"
  to = "/.netlify/identity/:splat"
  status = 200
  force = true

# 로그인 관련 CORS 설정
[[headers]]
  for = "/.netlify/functions/signin"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/api/signin"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/api/login"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS" 
    Access-Control-Allow-Headers = "Content-Type, Authorization"
  
[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/signin"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/signin"
  to = "/.netlify/functions/signin"
  status = 200
  force = true

# 사용자 정보 관련 리다이렉트
[[redirects]]
  from = "/api/auth/user"
  to = "/.netlify/functions/auth-user"
  status = 200
  force = true

# 세션 갱신 관련 리다이렉트
[[redirects]]
  from = "/api/refresh-token"
  to = "/.netlify/functions/refresh-token"
  status = 200
  force = true

# 운영자가 특정 사용자의 매장을 조회하는 라우트
[[redirects]]
  from = "/api/admin/users/:userId/stores"
  to = "/.netlify/functions/admin-user-stores"
  status = 200
  query = {userId = ":userId"}
  force = true

# 최종 폴백 리다이렉트 (SPA 지원)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200