[build]
  command = "echo 'Skipping build step - static site'"
  publish = "frontend"
  functions = "netlify/functions"

# 일반 API 경로 처리 (캐치올 리다이렉트)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# 매장 관련 API 경로 (쿼리 파라미터 사용)
[[redirects]]
  from = "/api/user/:userId/stores"
  to = "/.netlify/functions/user-stores"
  status = 200
  query = {userId = ":userId"}
  force = true

[[redirects]]
  from = "/api/stores/user/:userId/stores"
  to = "/.netlify/functions/stores-user-stores"
  status = 200
  query = {userId = ":userId"}
  force = true

[[redirects]]
  from = "/api/users/:userId/stores"
  to = "/.netlify/functions/users-stores"
  status = 200
  query = {userId = ":userId"}
  force = true

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200
  force = true
  
  [[redirects]]
  from = "/api/stats_detail*"
  to = "/.netlify/functions/stats-details:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/stats_details*"
  to = "/.netlify/functions/stats-details:splat"
  status = 200
  force = true

# 규칙 세부 정보 API (path 파라미터 사용)
[[redirects]]
  from = "/api/rules/:ruleId"
  to = "/.netlify/functions/rules-detail/:ruleId"
  status = 200
  force = true

# 최종 폴백 리다이렉트 (SPA 지원)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200