[build]
  command = "npm install && npm run build"
  publish = "frontend"
  functions = "netlify/functions"

# 기존 인증 리다이렉트 유지
[[redirects]]
  from = "/api/auth/user"
  to = "/.netlify/functions/auth-user"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/refresh-token"
  to = "/.netlify/functions/refresh-token"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/signin"
  to = "/.netlify/functions/signin"
  status = 200
  force = true

# 매장 관련 API 리다이렉트 추가
[[redirects]]
  from = "/api/stores/user-platform-stores"
  to = "/.netlify/functions/stores-user-platform"
  status = 200
  force = true

[[redirects]]
  from = "/api/user/:userId/stores"
  to = "/.netlify/functions/user-stores?userId=:userId"
  status = 200
  force = true

[[redirects]]
  from = "/api/stores/user/:userId/stores"
  to = "/.netlify/functions/stores-user-stores?userId=:userId"
  status = 200
  force = true

[[redirects]]
  from = "/api/users/:userId/stores"
  to = "/.netlify/functions/users-stores?userId=:userId"
  status = 200
  force = true

[[redirects]]
  from = "/api/stats/details"
  to = "/.netlify/functions/stats-details"
  status = 200
  force = true

[[redirects]]
  from = "/api/stores/all"
  to = "/.netlify/functions/stores-all"
  status = 200
  force = true

[[redirects]]
  from = "/api/stores/users"
  to = "/.netlify/functions/stores-users"
  status = 200
  force = true

[[redirects]]
  from = "/api/stores/assignments"
  to = "/.netlify/functions/stores-assignments"
  status = 200
  force = true

# 최종 폴백 리다이렉트
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200